plugins:
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: packages/plugins/plugin-build/bundles/@yarnpkg/plugin-build.js
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
